resources:
  repositories:
    - repository: 'SsdSim'  # identifier (A-Z, a-z, 0-9, and underscore)
      type: github
      name: 'DustParticle/SsdSim'
      ref: 'refs/heads/master'  # ref name to use, defaults to 'refs/heads/master'
      endpoint: 'Github connection 1'  # name of the service connection to use (for non-Azure Repos types)

queue:
  name: Hosted VS2017
  demands: msbuild

steps:
- checkout: self
- powershell: |
    git clone https://github.com/DustParticle/SsdSim.git
- task: VSBuild@1
  displayName: 'Build solution **/*.sln'
