resources:
  repositories:
    - repository: 'SsdSim'  # identifier (A-Z, a-z, 0-9, and underscore)
      type: github
      name: 'DustParticle/SsdSim'
      ref: 'refs/heads/master'  # ref name to use, defaults to 'refs/heads/master'
      endpoint: 'Github connection 1'  # name of the service connection to use (for non-Azure Repos types)

jobs:
- job: 'Main'
  strategy:
    maxParallel: 2
    matrix: 
      x64_Release:
        BuildConfiguration: release
        BuildPlatform: x64
        TestExe: './SsdSim/x64/Release/Test.exe'
      x64_Debug:
        BuildConfiguration: debug
        BuildPlatform: x64
        TestExe: './SsdSim/x64/Debug/Test.exe'
  steps:
  - script: git clone https://github.com/DustParticle/SsdSim.git
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
  - task: VSBuild@1
    displayName: 'Build solution **/*.sln'
    inputs:
      configuration: $(BuildConfiguration)
      platform: $(BuildPlatform)
  - powershell: $(TestExe)
    displayName: 'Running Tests'